name = "Together Optimized"
author = "CherryQuartzio"
version = "14.1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5560a76c2d9ae0303c9a2c41eadcef0ff9d39f73a2f1862199492fa6d69c6d2"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
