name = "Together Optimized"
author = "CherryQuartzio"
version = "14.0.0-beta.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ed72eaa94ea78505bcf3ff27b687d8376c2a84f48e6e6271f6612cf60d27392"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
