name = "Together Optimized"
author = "CherryQuartzio"
version = "15.0.0-alpha.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68c099c88f33991dbece018a19ecd13610eadfea5ffcb2a8acd86b63abc052ae"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
