name = "Fabulously Optimized"
author = "robotkoer"
version = "12.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d7e227f36f683f29a5249aa099dfb5afec5fdd7aaba5d7b3c84de929732fe7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
