name = "Fabulously Optimized"
author = "robotkoer"
version = "13.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0accbf9a30bc47be444d1459b426ced7f3999d0609169af5e7b85d9ec71dffa5"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
