name = "Fabulously Optimized"
author = "robotkoer"
version = "13.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40960437a497c37d42bffb1f93fbfec3c813ceaa378e1d01f2476b4eed366357"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
