name = "Fabulously Optimized"
author = "robotkoer"
version = "13.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "808eeeb28e9344f8bd97416ea15a000f5b480c075ae52985940f53dca9dba437"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
